version: 1

formatters:
  simple:
    format: '[%(asctime)s] %(threadName)s %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%dT%H:%M:%S'
  detailed:
    format: '[%(asctime)s] %(threadName)s %(levelname)s - %(message)s (%(filename)s:%(lineno)d - %(funcName)s)'
    datefmt: '%Y-%m-%dT%H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  sys_log_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: logs/sys.log
    maxBytes: 104857600  # 100MB
    backupCount: 5
    encoding: utf-8

  db_log_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: logs/db.log
    maxBytes: 104857600  # 100MB
    backupCount: 5
    encoding: utf-8


loggers:
  SysLogger:
    level: DEBUG
    handlers:
      - sys_log_file
    propagate: no

  DbLogger:
    level: INFO
    handlers:
      - db_log_file
    propagate: no

root:
  level: INFO
  handlers: [ console ]

