[tool.poetry]
name = "express-model"
version = "1.0.2"
description = ""
authors = ["yjsong <yjsong@interezen.co.kr>"]
readme = "README.md"
packages = [{ include = "express_model" }]

[tool.poetry.dependencies]
python = ">=3.9, <3.10"
express-utils = {path = "../../library/express-utils", develop = true}
kaleido = "0.2.1"

pycaret = "^3.3.2"
# The following packages are optional dependencies for PyCaret.
# The command 'poetry add pycaret[full]' causes conflicts.
shap = "^0.44.1"
umap-learn = "^0.5.6"
ydata-profiling = "^4.8.3"
explainerdashboard = "^0.4.7"
fairlearn = "^0.7.0"
xgboost = "^2.0.3"
catboost = "^1.2.5"
kmodes = "^0.12.2"
mlxtend = "^0.23.1"
statsforecast = "^1.5.0"
scikit-learn-intelex = "^2024.4.0"
hyperopt = "^0.2.7"
optuna = "^3.6.1"
optuna-integration = "^3.6.0"
scikit-optimize = "^0.10.1"
mlflow = "^2.13.1"
gradio = "^4.26.0"
boto3 = "^1.34.118"
fastapi = "^0.111.0"
uvicorn = "^0.30.1"
m2cgen = "^0.10.0"
evidently = "^0.4.25"
dask = "^2024.5.2"
distributed = "^2024.5.2"
fugue = "^0.8.7"
flask = "^2.3.3"
werkzeug = "^2.3.8"


[tool.poetry.group.dev.dependencies]
tabulate = "^0.9.0"


[[tool.poetry.source]]
name = "pypi-group"
url = "http://192.168.124.238:8001/repository/pypi-group/simple/"
priority = "supplemental"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

